# Kernel SVM

## Importing the libraries

In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix, accuracy_score

## Importing and rearranging the dataset

In [2]:
dataset = pd.read_csv('csv_files/loan_data.csv')
df_rearranged = dataset[['person_gender', 'person_education', 'person_home_ownership', 'loan_intent', 'previous_loan_defaults_on_file',
                         'person_age', 'person_income','person_emp_exp', 'loan_amnt', 'loan_int_rate', 'loan_percent_income',
                         'cb_person_cred_hist_length','credit_score', 'loan_status']]
df_rearranged.head()

person_gender person_education person_home_ownership loan_intent  \
0        female           Master                  RENT    PERSONAL   
1        female      High School                   OWN   EDUCATION   
2        female      High School              MORTGAGE     MEDICAL   
3        female         Bachelor                  RENT     MEDICAL   
4          male           Master                  RENT     MEDICAL   

  previous_loan_defaults_on_file  person_age  person_income  person_emp_exp  \
0                             No        22.0        71948.0               0   
1                            Yes        21.0        12282.0               0   
2                             No        25.0        12438.0               3   
3                             No        23.0        79753.0               0   
4                             No        24.0        66135.0               1   

   loan_amnt  loan_int_rate  loan_percent_income  cb_person_cred_hist_length  \
0    35000.0          16.02                 0.49                         3.0   
1     1000.0          11.14                 0.08                         2.0   
2     5500.0          12.87                 0.44                         3.0   
3    35000.0          15.23                 0.44                         2.0   
4    35000.0          14.27                 0.53                         4.0   

   credit_score  loan_status  
0           561            1  
1           504            0  
2           635            1  
3           675            1  
4           586            1

In [3]:
X = df_rearranged.iloc[:, :-1].values
y = df_rearranged.iloc[:, -1].values

## Encoding categorical data

In [4]:
le = LabelEncoder()
for i in range(0, 5):
  X[:, i] = le.fit_transform(X[:, i])


In [5]:
print(X)

[[0 4 3 ... 0.49 3.0 561]
 [0 3 2 ... 0.08 2.0 504]
 [0 3 0 ... 0.44 3.0 635]
 ...
 [1 0 3 ... 0.05 10.0 668]
 [1 1 3 ... 0.36 6.0 604]
 [1 3 3 ... 0.13 3.0 628]]


## Splitting the dataset into the Training set and Test set

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [7]:
print(X_train)

[[1 1 0 ... 0.3 3.0 645]
 [0 4 3 ... 0.03 4.0 610]
 [1 0 3 ... 0.13 3.0 572]
 ...
 [0 1 3 ... 0.17 9.0 672]
 [1 3 3 ... 0.25 7.0 548]
 [1 0 2 ... 0.26 2.0 644]]


In [8]:
print(y_train)

[0 0 0 ... 1 1 0]


In [9]:
print(X_test)

[[1 3 3 ... 0.33 4.0 614]
 [0 1 0 ... 0.16 4.0 623]
 [0 0 0 ... 0.06 7.0 663]
 ...
 [0 0 0 ... 0.04 3.0 647]
 [0 0 3 ... 0.15 2.0 705]
 [1 0 0 ... 0.36 5.0 679]]


In [10]:
print(y_test)

[1 0 0 ... 0 1 0]


## Feature Scaling

In [11]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [12]:
print(X_train)

[[ 0.90180309 -0.50286376 -1.18009575 ...  1.83635338 -0.74183567
   0.25024856]
 [-1.10888953  1.52319894  0.90264397 ... -1.26226342 -0.48294072
  -0.44264105]
 [ 0.90180309 -1.178218    0.90264397 ... -0.11462757 -0.74183567
  -1.19492119]
 ...
 [-1.10888953 -0.50286376  0.90264397 ...  0.34442677  0.81153402
   0.7847634 ]
 [ 0.90180309  0.84784471  0.90264397 ...  1.26253546  0.29374413
  -1.6700455 ]
 [ 0.90180309 -1.178218    0.20839739 ...  1.37729904 -1.00073061
   0.23045171]]


In [13]:
print(X_test)

[[ 0.90180309  0.84784471  0.90264397 ...  2.18064414 -0.48294072
  -0.36345367]
 [-1.10888953 -0.50286376 -1.18009575 ...  0.22966319 -0.48294072
  -0.18528205]
 [-1.10888953 -1.178218   -1.18009575 ... -0.91797267  0.29374413
   0.60659178]
 ...
 [-1.10888953 -1.178218   -1.18009575 ... -1.14749984 -0.74183567
   0.28984225]
 [-1.10888953 -1.178218    0.90264397 ...  0.1148996  -1.00073061
   1.43805931]
 [ 0.90180309 -1.178218   -1.18009575 ...  2.5249349  -0.22404577
   0.92334132]]


## Training the kernel SVM model

In [14]:
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)

SVC(random_state=0)

## Predicting the Test set results

In [15]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [1 0]
 [0 0]
 ...
 [0 0]
 [0 1]
 [0 0]]


## Making the Confusion Matrix

In [16]:
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[8364  399]
 [ 629 1858]]


0.9086222222222222